version: "3"
services:

  tmfrontend:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: tmfrontend-app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env.local
  