version: "3"
services:

  tmsbackend:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: tmsbackend
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  