version: "3"
services:

  team-manager-server:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: team-manager-server
    ports:
      - "7001:7001"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
  