export const projectMemberRoles = [
  "Manager",
  "Leader",
  "Developer",
  "Designer",
  "Content Writer",
  "Tester",
  "Scrum Master",
  "Product Owner",
  "QA Engineer",
  "Data Analyst",
  "Business Analyst",
  "Project Coordinator",
  "Technical Writer",
  "UX/UI Designer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Database Administrator",
  "Network Engineer",
  "Security Analyst",
  "DevOps Engineer",
  "System Architect",
  "Quality Assurance Specialist",
  "Technical Support",
  "Release Manager",
  "Operations Manager",
  "Customer Support Representative",
  "Sales Representative",
  "Marketing Specialist",
  "Copywriter",
  "Social Media Manager",
  "SEO Specialist",
  "Graphic Designer",
  "Video Editor",
  "Animator",
  "Content Strategist",
  "User Researcher",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Specialist",
  "Game Developer",
  "Mobile App Developer",
  "UI/UX Tester",
  "System Administrator",
  "IT Consultant",
  "Business Development Manager",
  "Legal Advisor",
  "Financial Analyst",
  "Project Analyst",
  "Logistics Coordinator",
  "Supply Chain Manager",
  "HR Specialist",
  "Recruiter",
  "Training Coordinator",
  "Event Planner",
  "Facilities Manager",
  "Procurement Specialist",
  "Market Researcher",
  "E-commerce Specialist",
  "CRM Specialist",
  "Content Marketing Manager",
  "Brand Manager",
  "Community Manager",
  "Public Relations Specialist",
  "Technical Recruiter",
  "Sales Engineer",
  "Solution Architect",
  "Database Developer",
  "Cloud Architect",
  "Customer Success Manager",
  "Business Intelligence Analyst",
  "Cybersecurity Analyst",
  "Legal Counsel",
  "Financial Controller",
  "ERP Specialist",
  "Health and Safety Officer",
  "Compliance Officer",
  "Ethics Officer",
  "Internal Auditor",
  "Sustainability Coordinator",
  "Learning and Development Specialist",
  "Procurement Officer",
  "Project Scheduler",
  "Usability Analyst",
  "Quantitative Analyst",
  "Investor Relations Specialist",
  "Supply Chain Analyst",
  "Localization Specialist",
  "Localization Tester",
  "Risk Analyst",
  "Database Administrator",
  "UI/UX Developer",
  "Multimedia Designer",
  "Technical Illustrator",
  "Application Support Analyst",
  "Brand Strategist",
  "Business Process Analyst",
  "Legal Researcher",
  "Financial Planner",
];

export const rolesWithMemberManagement = [
  "Manager",
  "Leader",
  "Project Coordinator",
  "Scrum Master",
];

export const rolesWithTaskManagement = [
  "Manager",
  "Leader",
  "Product Owner",
  "Project Coordinator",
  "Scrum Master",
];

