export const acceptableFiles = `
  application/pdf,
  video/mp4,
  video/avi,
  video/quicktime,
  video/x-matroska,
  video/x-ms-wmv,
  video/x-flv,
  video/mpeg,
  video/webm,
  video/3gpp,
  application/zip,
  application/x-msdownload,
  text/html,
  text/css,
  application/javascript,
  application/json,
  audio/mpeg,
  audio/wav,
  audio/ogg,
  audio/webm,
  audio/x-flac,
  audio/aac,
  audio/ogv,
  application/vnd.ms-excel,
  application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,
  application/msword,
  application/vnd.openxmlformats-officedocument.wordprocessingml.document,
  application/vnd.ms-powerpoint,
  application/vnd.openxmlformats-officedocument.presentationml.presentation,
  application/x-rar-compressed,
  application/x-7z-compressed,
  application/x-tar
`.replace(/\s+/g, "");

export const acceptableExtensions = {
  audio: [
    "mp3",
    "wav",
    "aac",
    "flac",
    "ogg",
    "m4a",
    "wma",
    "aiff",
    "alac",
    "opus",
    "amr",
    "pcm",
    "mid",
    "midi",
    "aif",
    "ra",
    "weba",
    "ogv",
    "mpeg",
  ],
  video: ["mp4", "avi", "mov", "mkv", "wmv", "flv", "webm", "3gpp"],
  document: ["pdf", "xls", "xlsx", "doc", "docx", "ppt", "pptx"],
  archive: ["zip", "rar", "7z", "tar"],
  executable: ["exe"],
  web: ["html", "css", "js", "json"],
};
