import { INotification } from "@/interfaces/notification.interface";

export const demoNotificationData: INotification[] = [
  {
    id: 1,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "System Update",
      message: "A new update has been installed.",
      link: "/updates/1",
      data: { sendBy: "Admin" },
    },
    recipient: { userId: "user1", name: "John Doe" },
  },
  {
    id: 2,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Password Change",
      message: "Your password has been changed.",
      link: "/security/2",
      data: { sendBy: "Security Team" },
    },
    recipient: { userId: "user2", name: "Jane Smith" },
  },
  {
    id: 3,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "New Message",
      message: "You have received a new message.",
      link: "/messages/3",
      data: { sendBy: "Alice" },
    },
    recipient: { userId: "user3", name: "Alice Johnson" },
  },
  {
    id: 4,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Login Alert",
      message: "A login attempt was made from a new device.",
      link: "/security/4",
      data: { sendBy: "Security Team" },
    },
    recipient: { userId: "user4", name: "Bob Brown" },
  },
  {
    id: 5,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Profile Updated",
      message: "Your profile has been updated successfully.",
      link: "/profile/5",
      data: { sendBy: "Admin" },
    },
    recipient: { userId: "user5", name: "Charlie Davis" },
  },
  {
    id: 6,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Account Suspended",
      message: "Your account has been temporarily suspended.",
      link: "/account/6",
      data: { sendBy: "Support" },
    },
    recipient: { userId: "user6", name: "Daniel Evans" },
  },
  {
    id: 7,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Subscription Expiring",
      message: "Your subscription will expire soon.",
      link: "/subscription/7",
      data: { sendBy: "Admin" },
    },
    recipient: { userId: "user7", name: "Emily Frank" },
  },
  {
    id: 8,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "New Feature",
      message: "A new feature has been added to your account.",
      link: "/features/8",
      data: { sendBy: "Product Team" },
    },
    recipient: { userId: "user8", name: "Grace Hill" },
  },
  {
    id: 9,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Payment Failed",
      message: "Your recent payment attempt failed.",
      link: "/billing/9",
      data: { sendBy: "Billing" },
    },
    recipient: { userId: "user9", name: "Henry Irwin" },
  },
  {
    id: 10,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Welcome",
      message: "Welcome to our platform!",
      link: "/welcome/10",
      data: { sendBy: "Admin" },
    },
    recipient: { userId: "user10", name: "Ivy James" },
  },
  {
    id: 11,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Email Changed",
      message: "Your email address has been changed.",
      link: "/profile/11",
      data: { sendBy: "Security Team" },
    },
    recipient: { userId: "user11", name: "Jack Kelly" },
  },
  {
    id: 12,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Survey",
      message: "Please take a moment to fill out our survey.",
      link: "/survey/12",
      data: { sendBy: "Support" },
    },
    recipient: { userId: "user12", name: "Kara Lewis" },
  },
  {
    id: 13,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Security Alert",
      message: "Suspicious activity detected on your account.",
      link: "/security/13",
      data: { sendBy: "Security Team" },
    },
    recipient: { userId: "user13", name: "Liam Martinez" },
  },
  {
    id: 14,
    type: "info",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Backup Completed",
      message: "Your data backup was completed successfully.",
      link: "/backup/14",
      data: { sendBy: "Support" },
    },
    recipient: { userId: "user14", name: "Mia Nelson" },
  },
  {
    id: 15,
    type: "alert",
    createdAt: new Date(),
    read: true,
    content: {
      title: "Account Recovered",
      message: "Your account has been recovered.",
      link: "/account/15",
      data: { sendBy: "Support" },
    },
    recipient: { userId: "user15", name: "Noah Owen" },
  },
  {
    id: 16,
    type: "info",
    createdAt: new Date(),
    read: false,
    content: {
      title: "New Connection",
      message: "You have a new connection request.",
      link: "/connections/16",
      data: { sendBy: "Olivia" },
    },
    recipient: { userId: "user16", name: "Olivia Parker" },
  },
  {
    id: 17,
    type: "alert",
    createdAt: new Date(),
    read: false,
    content: {
      title: "Two-Factor Authentication Enabled",
      message: "You have enabled two-factor authentication.",
      link: "/security/17",
      data: { sendBy: "Security Team" },
    },
    recipient: { userId: "user17", name: "Patrick Quinn" },
  },
  {
    id: 18,
    type: "info",
    createdAt: new Date(),
    read: false,
    content: {
      title: "Meeting Reminder",
      message: "You have an upcoming meeting scheduled.",
      link: "/meetings/18",
      data: { sendBy: "Admin" },
    },
    recipient: { userId: "user18", name: "Quincy Rose" },
  },
  {
    id: 19,
    type: "alert",
    createdAt: new Date(),
    read: false,
    content: {
      title: "Unusual Login Location",
      message: "Your account was accessed from a new location.",
      link: "/security/19",
      data: { sendBy: "Security Team" },
    },
    recipient: { userId: "user19", name: "Rachel Scott" },
  },
  {
    id: 20,
    type: "info",
    createdAt: new Date(),
    read: false,
    content: {
      title: "Upgrade Available",
      message: "A new upgrade is available for your account.",
      link: "/upgrade/20",
      data: { sendBy: "Admin" },
    },
    recipient: { userId: "user20", name: "Samuel Turner" },
  },
];
