export const popularTeamData = [
  {
    id: "1",
    name: "Alpha Innovators",
    category: "Technology",
    description:
      "Leading the charge in tech innovations with cutting-edge projects.",
    image: "https://example.com/images/alpha-innovators.jpg",
    admin: { name: "John Doe", id: "admin1" },
    activeMembers: 25,
    pendingMembers: 5,
    projects: 12,
    animation: "flip-right",
  },
  {
    id: "2",
    name: "Creative Coders",
    category: "Design",
    description:
      "A group of passionate designers and developers building creative solutions.",
    image: "https://example.com/images/creative-coders.jpg",
    admin: { name: "Jane Smith", id: "admin2" },
    activeMembers: 18,
    pendingMembers: 2,
    projects: 8,
    animation: "flip-left",
  },
  {
    id: "3",
    name: "Marketing Masters",
    category: "Marketing",
    description: "Experts in digital marketing and branding strategies.",
    image: "https://example.com/images/marketing-masters.jpg",
    admin: { name: "Alice Johnson", id: "admin3" },
    activeMembers: 30,
    pendingMembers: 4,
    projects: 15,
    animation: "flip-up",
  },
  {
    id: "4",
    name: "Data Dynamos",
    category: "Data Science",
    description:
      "Harnessing the power of data to drive insights and decisions.",
    image: "https://example.com/images/data-dynamos.jpg",
    admin: { name: "Bob Brown", id: "admin4" },
    activeMembers: 20,
    pendingMembers: 3,
    projects: 10,
    animation: "flip-down",
  },
  {
    id: "5",
    name: "Finance Gurus",
    category: "Finance",
    description:
      "Managing financial portfolios and providing investment advice.",
    image: "https://example.com/images/finance-gurus.jpg",
    admin: { name: "Carol White", id: "admin5" },
    activeMembers: 22,
    pendingMembers: 6,
    projects: 9,
    animation: "flip-right",
  },
  {
    id: "6",
    name: "Healthcare Heroes",
    category: "Healthcare",
    description: "Innovating healthcare solutions for a better tomorrow.",
    image: "https://example.com/images/healthcare-heroes.jpg",
    admin: { name: "David Green", id: "admin6" },
    activeMembers: 28,
    pendingMembers: 7,
    projects: 14,
    animation: "flip-left",
  },
  {
    id: "7",
    name: "EduExperts",
    category: "Education",
    description:
      "Transforming education through innovative learning solutions.",
    image: "https://example.com/images/eduexperts.jpg",
    admin: { name: "Emma Davis", id: "admin7" },
    activeMembers: 26,
    pendingMembers: 3,
    projects: 11,
    animation: "flip-up",
  },
  {
    id: "8",
    name: "Green Energy",
    category: "Environment",
    description: "Promoting sustainable energy solutions for a greener planet.",
    image: "https://example.com/images/green-energy.jpg",
    admin: { name: "Frank Harris", id: "admin8" },
    activeMembers: 19,
    pendingMembers: 2,
    projects: 7,
    animation: "flip-down",
  },
  {
    id: "9",
    name: "Retail Revamp",
    category: "Retail",
    description:
      "Revolutionizing the retail industry with innovative strategies.",
    image: "https://example.com/images/retail-revamp.jpg",
    admin: { name: "Grace Lee", id: "admin9" },
    activeMembers: 24,
    pendingMembers: 4,
    projects: 10,
    animation: "flip-right",
  },
  {
    id: "10",
    name: "Logistics Legends",
    category: "Logistics",
    description:
      "Optimizing supply chains and logistics management for efficiency.",
    image: "https://example.com/images/logistics-legends.jpg",
    admin: { name: "Henry Wilson", id: "admin10" },
    activeMembers: 23,
    pendingMembers: 3,
    projects: 12,
    animation: "flip-left",
  },
];
