export const popularProjectData = [
  {
    id: "1",
    team: { name: "Alpha Team", id: "alpha" },
    user: { id: "user1", name: "John Doe" },
    name: "React Native Chat App",
    category: "Mobile Development",
    members: 8,
    tasks: 15,
    animation: "flip-left",
  },
  {
    id: "2",
    team: { name: "Beta Team", id: "beta" },
    user: { id: "user2", name: "Jane Smith" },
    name: "Next.js E-Commerce Platform",
    category: "Web Development",
    members: 5,
    tasks: 12,
    animation: "flip-right",
  },
  {
    id: "3",
    team: { name: "Gamma Team", id: "gamma" },
    user: { id: "user3", name: "Alice Johnson" },
    name: "Figma Design System",
    category: "UI/UX Design",
    members: 6,
    tasks: 18,
    animation: "flip-up",
  },
  {
    id: "4",
    team: { name: "Delta Team", id: "delta" },
    user: { id: "user4", name: "Michael Brown" },
    name: "TensorFlow Image Classifier",
    category: "Data Science",
    members: 10,
    tasks: 20,
    animation: "flip-down",
  },
  {
    id: "5",
    team: { name: "Epsilon Team", id: "epsilon" },
    user: { id: "user5", name: "Sophia Wilson" },
    name: "Scikit-Learn Model Trainer",
    category: "Machine Learning",
    members: 7,
    tasks: 14,
    animation: "flip-right",
  },
  {
    id: "6",
    team: { name: "Zeta Team", id: "zeta" },
    user: { id: "user6", name: "Ethan Davis" },
    name: "AWS Cloud Deployment",
    category: "Cloud Computing",
    members: 9,
    tasks: 17,
    animation: "flip-left",
  },
  {
    id: "7",
    team: { name: "Eta Team", id: "eta" },
    user: { id: "user7", name: "Mia Garcia" },
    name: "Ethereum Smart Contracts",
    category: "Blockchain",
    members: 4,
    tasks: 11,
    animation: "flip-up",
  },
  {
    id: "8",
    team: { name: "Theta Team", id: "theta" },
    user: { id: "user8", name: "Oliver Martinez" },
    name: "GPT-3 Text Generation",
    category: "AI Development",
    members: 12,
    tasks: 25,
    animation: "flip-down",
  },
  {
    id: "9",
    team: { name: "Iota Team", id: "iota" },
    user: { id: "user9", name: "Amelia Lee" },
    name: "Penetration Testing Suite",
    category: "Cybersecurity",
    members: 5,
    tasks: 13,
    animation: "flip-right",
  },
  {
    id: "10",
    team: { name: "Kappa Team", id: "kappa" },
    user: { id: "user10", name: "James Wilson" },
    name: "Kubernetes CI/CD Pipeline",
    category: "DevOps",
    members: 6,
    tasks: 16,
    animation: "flip-left",
  },
];
