export const notificationEnums = {
  TASK_ASSIGNED: "Task assigned",
  TASK_COMPLETED: "Task completed",
  TASK_OVERDUE: "Task overdue",
  TASK_UPDATED: "Task updated",
  TASK_DELETED: "Task deleted",
  TASK_COMMENTED: "Comment added to task",
  TASK_REASSIGNED: "Task reassigned",
  PROJECT_CREATED: "Project created",
  PROJECT_UPDATED: "Project updated",
  PROJECT_DELETED: "Project deleted",
  PROJECT_COMPLETED: "Project completed",
  PROJECT_OVERDUE: "Project overdue",
  PROJECT_MEMBER_ADDED: "Member added to project",
  PROJECT_MEMBER_REMOVED: "Member removed from project",
  TEAM_INVITATION: "Team invitation received",
  TEAM_JOINED: "Joined team",
  TEAM_LEFT: "Left team",
  TEAM_UPDATED: "Team updated",
  TEAM_MEMBER_ADDED: "Member added to team",
  TEAM_MEMBER_REMOVED: "Member removed from team",
  COMMENT_MENTION: "Mentioned in a comment",
  USER_MENTIONED: "User mentioned",
  COMMENT_ADDED: "Comment added",
  FILE_UPLOADED: "File uploaded",
  FILE_DELETED: "File deleted",
  DEADLINE_APPROACHING: "Deadline approaching",
  REMINDER: "Reminder",
  MESSAGE_RECEIVED: "Message received",
  ANNOUNCEMENT: "Announcement",
  USER_PROFILE_UPDATED: "User profile updated",
  PERMISSION_CHANGED: "Permission changed",
  SYSTEM_ALERT: "System alert",
  NEW_FEATURE: "New feature available",
};
